### ISSUE TITLE
你好，感谢你的脚本。但是我一开始就无法运行

### ISSUE THREAD

**Issue by winter07** [brendonjkding/fgoScript#1]
我用的是6s，按音量播放脚本就会直接播放结束，我的队伍配置是 伯爵 CBA 孔明 助战CBA 随意 随意。助战选择：自动，礼装：任意，从者：cba，换人礼装，技能设定为1t: 9 8 7a 4a 12op 7a 2; 2t: 6a; 3t: 1 5 8 9a 10。队伍性质是绿卡，指定助战职介：术，其他都是默认。
一运行脚本就会显示“播放结束”

**Comment by brendonjkding** [comment]
> 我用的是6s，按音量播放脚本就会直接播放结束，我的队伍配置是 伯爵 CBA 孔明 助战CBA 随意 随意。助战选择：自动，礼装：任意，从者：cba，换人礼装，技能设定为1t: 9 8 7a 4a 12op 7a 2; 2t: 6a; 3t: 1 5 8 9a 10。队伍性质是绿卡，指定助战职介：术，其他都是默认。
> 一运行脚本就会显示“播放结束”

你运行的是生成的新文件吗，点右上角刷新才会显示

**Comment by winter07** [comment]
> > 我用的是6s，按音量播放脚本就会直接播放结束，我的队伍配置是 伯爵 CBA 孔明 助战CBA 随意 随意。助战选择：自动，礼装：任意，从者：cba，换人礼装，技能设定为1t: 9 8 7a 4a 12op 7a 2; 2t: 6a; 3t: 1 5 8 9a 10。队伍性质是绿卡，指定助战职介：术，其他都是默认。
> > 一运行脚本就会显示“播放结束”
> 
> 你运行的是生成的新文件吗，点右上角刷新才会显示

是先运行的main.lua后生成了一个新的lua，然后运行的新的lua的，能麻烦你帮我配置有一个，我丢进去试试吗？谢谢

**Comment by brendonjkding** [comment]
> > > 我用的是6s，按音量播放脚本就会直接播放结束，我的队伍配置是 伯爵 CBA 孔明 助战CBA 随意 随意。助战选择：自动，礼装：任意，从者：cba，换人礼装，技能设定为1t: 9 8 7a 4a 12op 7a 2; 2t: 6a; 3t: 1 5 8 9a 10。队伍性质是绿卡，指定助战职介：术，其他都是默认。
> > > 一运行脚本就会显示“播放结束”
> > 
> > 
> > 你运行的是生成的新文件吗，点右上角刷新才会显示
> 
> 是先运行的main.lua后生成了一个新的lua，然后运行的新的lua的，能麻烦你帮我配置有一个，我丢进去试试吗？谢谢

你加我qq吧 1277342721

**Comment by winter07** [comment]
已经解决这个问题了，需要购买触摸精灵序列号才能正常工作

**Comment by saintkai0930** [comment]
大佬，我买了序列号也是一开始就播放结束了，是啥回事呀。。。

**Comment by brendonjkding** [comment]
这个issue之前是用QQ交流解决了(具体问题忘了，但已修复)。删除的comment内容是说需要购买序列号，后来我自己试了下是可以试用的，为了避免误导所以删除了那条comment。
