### ISSUE TITLE
脚本一运行就报错

### ISSUE THREAD

**Issue by saintkai0930** [brendonjkding/fgoScript#2]
你好，

非常感谢你的脚本。我在运行新生成的和搓丸子的脚本时，遇到截图中的报错，麻烦帮忙看看。

谢谢。[](url)
![1](https://user-images.githubusercontent.com/72136046/94752026-a3192080-03bc-11eb-9e5b-80487e0c4e32.png)

**Comment by brendonjkding** [comment]
应该是触摸的版本太低了，toast函数在某个版本之后才有的
