### ISSUE TITLE
连续出击窗口好像会导致软件呆住

### ISSUE THREAD

**Issue by a08381** [brendonjkding/fgoScript#4]
![image](https://user-images.githubusercontent.com/2505002/132631675-a7eb13a9-e5b3-408a-b9ad-695866e3e713.png)

![image](https://user-images.githubusercontent.com/2505002/132631749-a8c25ff4-050f-4dfe-b5e9-43ebae6e436e.png)

**Comment by brendonjkding** [comment]
打了两天本其它bug都有碰到这个还没能复现

**Comment by a08381** [comment]
> 打了两天本其它bug都有碰到这个还没能复现

我在lib_fgo的第1228行插入了5秒的延迟解决了这个问题，原因可能是wait_quit_mission函数在我的手机上没有正确执行
