### ISSUE TITLE
请教下关于指令卡识别

### ISSUE THREAD

**Issue by kid424** [brendonjkding/fgoScript#7]
首先感谢作者开源脚本，社畜也能把苹果清了233。

然后就是请教下关于用guai_points识别卡是打手还是拐的这部分（方法名get_card_intrinsic_attributes），我看目前精度是75，会出现一些误识别的样子。比如仇凛3破会被认成梅林，总司3个阶段似乎都会被认成拐（具体是谁不记得了）。不知道大佬有没有什么建议可以提高一下识别的准确度呢？

**Comment by brendonjkding** [comment]
确实可能会误识别。不知道是不是个别机型原因，现在的画面渲染结果变化程度好像越来越大了，精读调低了会误识别，调高了可能会识别不出来，我暂时没想出什么好办法

**Comment by kid424** [comment]
感谢回复。方便的话请问下大佬开发的时候是基于哪种设备取色和调试呢？

**Comment by brendonjkding** [comment]
6s为主 偶尔7
